# Generated by Django 5.1 on 2024-10-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_like_author_remove_like_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('create', 'Can create post'), ('update', 'Can update post'), ('read', 'Can read post')]},
        ),
    ]
