# Generated by Django 5.1 on 2024-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
